name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: built
      - name: Build
        run: ./run.sh merge-and-push
        env:
          GIT_AUTHOR_NAME: "Automatic updater [bot]"
          GIT_AUTHOR_EMAIL: "sleepdiary-bot@pileofstuff.org"
          GIT_COMMITTER_NAME: "Automatic updater [bot]"
          GIT_COMMITTER_EMAIL: "sleepdiary-bot@pileofstuff.org"
